name: aqua-code-scan-agent
on:
  push:
    branches:
      - agent
  workflow_dispatch:

jobs:
  scan-only:
    name: Aqua code scan (agent branch)
    runs-on: ubuntu-latest
    environment: crossdep
    env:
      AQUA_KEY: ${{ secrets.AQUA_KEY }}
      AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
      TRIVY_RUN_AS_PLUGIN: aqua
      TRIVY_USERNAME: ${{ secrets.TRIVY_USERNAME }}
      TRIVY_PASSWORD: ${{ secrets.TRIVY_PASSWORD }}
      TRIVY_DB_REPOSITORY: registry.aquasec.com/trivy-db:2
      TRIVY_JAVA_DB_REPOSITORY: registry.aquasec.com/trivy-java-db:1
      TRIVY_CHECKS_BUNDLE_REPOSITORY: registry.aquasec.com/trivy-checks:1
      OVERRIDE_BRANCH: agent
      OVERRIDE_SOURCE_BRANCH: agent

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 6144
          remove-android: true
          remove-dotnet: true
          remove-haskell: true
          remove-docker-images: true
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo docker system prune -af
          df -h
      - name: Run Aqua scanner
        uses: docker://aquasec/aqua-scanner:latest-limited
        with:
          args: trivy fs --scanners config,vuln,secret . --sast
